### PR TITLE
Update CI build and prepare for 1.1.0

### PR DESCRIPTION
**Pull request by oschwald**

### CODE REVIEW

**Comment by oschwald** [comment]
@am11, have you seen [this Travis failure](https://travis-ci.org/maxmind/minfraud-api-dotnet/jobs/166575675) with .NET Core on OS X before? I initially tried to fix it by updating OpenSSL in Homebrew, but that did not seem to work.

**Comment by am11** [comment]
@oschwald, I think we don't need to install OpenSSL by ourselves, since we are using TravisCI OOTB dotnet configuration (which already has OpenSSL installed). Can you try without it like we have in MaxMind-DB-Reader-dotnet repo?

**Comment by oschwald** [comment]
@am11, that is what I tried first. I only tried this when I got the error and this was proposed as a workaround. I think [this build](https://travis-ci.org/maxmind/minfraud-api-dotnet/jobs/166565123) was from before I added the attempted workaround.

**Comment by oschwald** [comment]
The same thing seems to be happening with [MaxMind.Db builds](https://travis-ci.org/maxmind/MaxMind-DB-Reader-dotnet/jobs/160561095) now with no CI changes since your PR.

**Comment by oschwald** [comment]
I've disabled the OS X .NET Core build in this branch for now.

**Pull request merged**
